#!/usr/bin/env python3
# ──────────────────────────────────────────────────────────────────────
# GuardGrid V3 – Advanced Security Concept
# File:    main.py
# Purpose: Entry point for the GuardGrid V3 simulation.
# ──────────────────────────────────────────────────────────────────────

import sys
import time
from config import N_USERS, SCALE, EPSILON, MAX_READING, DKG_K, DKG_T, MASK_BOUND, GROUP_BITS
from crypto.dh import dh_params
from crypto.mife_wrapper import MIFEWrapper
from schemes.guardgrid_v3 import (
    v3_phase0_setup,
    v3_phase1_key_exchange,
    v3_phase2_collect
)
from entities.smart_meter_v3 import SmartMeterV3
from entities.agg_gateway_v3 import AggGatewayV3
from entities.control_center_v3 import ControlCenterV3
from entities.cloud_server_v3 import CloudServerV3
from data.loader import load_readings

def run_simulation(n_users: int):
    print(f"\n{'='*60}")
    print(f" GuardGrid V3 Post-Quantum Simulation ({n_users} Meters)")
    print(f"{'='*60}")
    
    # Load Real Data
    print("\n[Data] Loading smart meter readings...")
    readings = load_readings(n_users)
    print(f"       Raw readings (scaled): {readings}")
    expected_sum = sum(readings)
    print(f"       Expected cleartext sum: {expected_sum}")
    
    # Phase 0: Setup & DKG
    print("\n[Phase 0] Setup & Distributed Key Generation...")
    start = time.time()
    # We borrow the p, g generation from DH for the group params
    p, g = dh_params(GROUP_BITS)
    
    sys_params = v3_phase0_setup(DKG_K, DKG_T, p, g)
    print(f"       Global PK generated by {DKG_K} nodes (T={DKG_T})")
    
    # MIFE Setup (TTP logically still does this in MIFE lib, though DKG should)
    mife_params = MIFEWrapper.setup(n_users)
    pk_y = mife_params["pk"]
    sk_y = mife_params["sk"]
    slot_keys = mife_params["slot_keys"]
    print(f"       MIFE parameters initialized.")
    print(f"       Phase 0 Time: {time.time()-start:.3f}s")
    
    # Phase 1: PQ Key Exchange
    print("\n[Phase 1] Post-Quantum ML-KEM-768 Key Exchange...")
    start = time.time()
    cc_keys = v3_phase1_key_exchange(n_users)
    print(f"       Generated {n_users} ML-KEM session keys.")
    print(f"       Phase 1 Time: {time.time()-start:.3f}s")
    
    # Phase 2: Collect & Encrypt
    print("\n[Phase 2] Smart Meters: DP Noise + Encrypt + ZKP + Pad...")
    start = time.time()
    
    meters = [SmartMeterV3(i, slot_keys[i], cc_keys[i]["ek"], sys_params) for i in range(n_users)]
    
    bundles = []
    for i, meter in enumerate(meters):
        bundle = meter.report_reading(readings[i], EPSILON, MAX_READING, MASK_BOUND)
        bundles.append(bundle)
        
    print(f"       {n_users} bundles generated (Ciphertext, LHH, ZKP range proof).")
    print(f"       DP Epsilon per meter: {EPSILON}")
    print(f"       Phase 2 Time: {time.time()-start:.3f}s")
    
    # Phase 3: Aggregation & Verification
    print("\n[Phase 3] AG & CC: Verify ZKPs, Aggregate MIFE, Check LHH, Unmask...")
    start = time.time()
    
    ag = AggGatewayV3(pk_y, sys_params)
    # AG executes aggregation (MIFE + LHH)
    mife_res, h_star = ag.execute_aggregation(bundles, sk_y, p)
    print(f"       AG completed MIFE inner product. Result: {mife_res}")
    
    # CC verifies and unmasks
    cc = ControlCenterV3(cc_keys, sys_params)
    final_aggregate = cc.verify_and_unmask(mife_res, h_star, bundles, MASK_BOUND)
    print(f"       CC verified LHH and unmasked session keys.")
    print(f"       Phase 3 Time: {time.time()-start:.3f}s")
    
    print("\n[Results]")
    print(f"       Expected cleartext sum : {expected_sum}")
    print(f"       Decrypted noisy sum    : {final_aggregate}")
    error = abs(expected_sum - final_aggregate)
    print(f"       DP Noise Impact        : {error} ({(error/expected_sum)*100:.2f}%)")
    
    # Phase 4: Cloud
    print("\n[Phase 4] Cloud Server Lattice FE Query...")
    start = time.time()
    cloud = CloudServerV3()
    # CC encrypts aggregate for Cloud using Lattice FE
    lfe_pk = sys_params["lfe_pk"]
    lfe_msk = sys_params["lfe_msk"]
    
    # Encrypt aggregate
    from crypto.lattice_fe import LatticeFE
    lfe = LatticeFE()
    ct_cloud = lfe.encrypt(lfe_pk, final_aggregate)
    
    # Cloud evaluates f(x) = 2*x + 100
    a, b_const = 2, 100
    sk_a = lfe.func_keygen(lfe_msk, a)
    result = cloud.evaluate_query(ct_cloud, sk_a, a, b_const)
    
    expected_result = a * final_aggregate + b_const
    print(f"       Cloud computed f(x)=2x+100: {result}")
    print(f"       Expected result           : {expected_result}")
    if result == expected_result:
        print("       [SUCCESS] Lattice FE query matches expected.")
    else:
        print("       [WARNING] Lattice FE query mismatch (expected with simulated LWE decoding).")
    print(f"       Phase 4 Time: {time.time()-start:.3f}s")
    
    print(f"\n{'='*60}")
    print(" Simulation Complete.")
    print(f"{'='*60}\n")

if __name__ == "__main__":
    n = N_USERS
    if len(sys.argv) > 1:
        if sys.argv[1].isdigit():
            n = int(sys.argv[1])
            
    run_simulation(n)
